### PR TITLE
Add support for unix domain sockets

### PR DESCRIPTION
**Pull request by najtin**
I would really like to use timetagger and i would really like to be able to run it on unix domain sockets. Since timetagger depends on asgineer, i added support for unix domain sockets. Are you happy with these changes? What do you need to get this merged?

PS: Thank you very much for maintaining and creating timetagger! It's awesome.

### CODE REVIEW

**Comment by almarklein** [comment]
Thanks for the contribution, looks clean and reasonable! Does hypercorn *just work* without chaning something here?

**Comment by najtin** [comment]
> Does hypercorn just work without chaning something here?

Yes it just works because it does not separate host and port and just uses the --bind flag.

**Comment by najtin** [comment]
These test currently fail because the web servers are not in the test dependencies yet. I will take a look into that later this evening.

**Comment by najtin** [comment]
I think this will fix the errors in the ci pipeline, but i can't run the pipeline myself.

**Comment by almarklein** [comment]
Two builds fail on the new test, and some linting errors left:
```
Run pyflakes .
./tests/test_unixsocket.py:5:1: 'os' imported but unused
./tests/test_unixsocket.py:8:1: 'common.get_backend' imported but unused
```

**Comment by najtin** [comment]
I fixed the pyflakes error. The 37 error requires monkey patching, because Literal from typing was only stabilized in python 3.8. The 3.12, the uvicorn and daphne are about the same error. For some reason the directory does not seem to be there? [Someone on stackoverflow](https://stackoverflow.com/questions/78915695/python-temporary-directory-access-is-denied-error-for-external-subprocesses-on) has the same problem with 3.12 and none of the versions before that.

**Comment by almarklein** [comment]
We can drop support for 3.7, maybe even 3.8. Just delete these lines:

https://github.com/almarklein/asgineer/blob/5074cd17f4f55ac8407401a3b0bef77a92ab29f9/.github/workflows/ci.yml#L63-L66

I tried to run the test locally with hypercorn, and it seems to work fine on 3.12. If the issue has to do with rights, maybe you can try using a file in the local path for the websocket (add to .gitignore if necessary).

**Comment by najtin** [comment]
I dropped 3.7 and manage to run the [CI on my branch](https://github.com/najtin/asgineer/actions/runs/11466304442/job/31906680290). (I had to add a commit, but it just adds an empty file. The code is the same as on my master.) What i changed is, that the test manually cleans the directory instead of relying on the ContextManager. It could actually have been a race condition, were the web server was a little slow to start in python 3.12. The test would try to open the socket file and fail, reach the end of the loop and clean up, thus removing the directory. When the web server then tries to create the socket, the folder is already gone. To circumvent this i added a loop. The test will now retry 2 more times if the initial connection fails.

**Comment by najtin** [comment]
> If the issue has to do with rights, maybe you can try using a file in the local path for the websocket (add to .gitignore if necessary).

Thanks for the suggestion. I thought about that, but it turns out that [tempfile does this by default as a last resort](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir). 

Thank you for engaging in this PR. :+1:

**Comment by almarklein** [comment]
Thanks for your contribution!

**Comment by almarklein** [comment]
Released a new version

**Pull request merged**
